BlogMvc/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogMvc.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BlogMvc.Models
{
    public class BlogController : Controller
    {
        private readonly BlogMvcContext _context;
        public BlogController(BlogMvcContext context)
        {
            _context = context;
        }

        // GET: Blog
        public async Task<IActionResult>Index()
        {
            return View(await _context.Article.ToListAsync());
        }

        // GET: Blog/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var article = await _context.Article
                .Include(y => y.ArticleTags)
                .ThenInclude(y => y.Tag)
                .FirstOrDefaultAsync(m => m.ID == id);
            

            if (article == null)
                return NotFound();

            return View(article);
        }

        // GET: Blog/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ArticleDate,Content,ArticleTags")] ArticleViewModel articleVM)
        {
            if (ModelState.IsValid)
            {
                // etiket işlemleri
                // etiketleri string array olarak al.
                // her etiket veritabanına eklimi diye bak
                // ekliyse, listeye ekle devam et.
                // değilse veritabanına ekle ve listeleye ekle devam et.
                string[] tagArray = null;
                char[] splitChar = { ',' };
                tagArray = articleVM.ArticleTags.Split(splitChar);

                List<Tag> articleTags = new List<Tag>();

                foreach (var item in tagArray)
                {
                    string strTag = item.Replace(" ", "");
                    bool isTagExist = _context.Tags.Any(x => x.TagName == strTag);

                    if (isTagExist == true) // etiket var listeye ekle
                    {
                        var tag = _context.Tags.FirstOrDefault(x => x.TagName == strTag);
                        articleTags.Add(tag);
                    }
                    else // etiket yok veritabanına ekle
                    {
                        Tag tag = new Tag();
                        tag.TagName = strTag;

                        _context.Add(tag);
                        _context.SaveChanges();

                        articleTags.Add(tag);
                    }
                }


                Article article = new Article();
                article.ArticleContent = articleVM.Content;
                article.ArticleDate = articleVM.ArticleDate;
                article.ArticleTitle = articleVM.Title;
                _context.Add(article);
                await _context.SaveChangesAsync();


                List<ArticleTags> articleTags1 = new List<ArticleTags>();
                foreach (var item in articleTags)
                {
                    ArticleTags at = new ArticleTags();
                    at.ArticleID = article.ID;
                    at.TagID = item.ID;

                    articleTags1.Add(at);
                }

                article.ArticleTags = articleTags1;
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View(articleVM);
        }

        // GET: Blog/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Article.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }
            return View(article);
        }

        // POST: Blog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ArticleTitle,ArticleDate,ArticleContent")] Article article)
        {
            if (id != article.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(article);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(article);
        }

        // GET: Blog/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Article
                .FirstOrDefaultAsync(m => m.ID == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Blog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var article = await _context.Article.FindAsync(id);
            _context.Article.Remove(article);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticleExists(int id)
        {
            return _context.Article.Any(e => e.ID == id);
        }
        
      
    }
}

BlogMvc/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogMvc.Models;

namespace BlogMvc.Controllers
{
    public class TagsController : Controller
    {
        private readonly BlogMvcContext _context;

        public TagsController(BlogMvcContext context)
        {
            _context = context;
        }

        // GET: Tags
        public async Task<IActionResult> Index(int tagID)
        {


            var articles = (from article in _context.Article
                           join articleTag in _context.ArticleTags on article.ID equals articleTag.ArticleID
                           where articleTag.TagID == tagID
                           select article).ToList();


            if (articles == null)
                return NotFound();
    
            return View(articles);

        }

        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // GET: Tags/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,TagName")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags.FindAsync(id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,TagName")] Tag tag)
        {
            if (id != tag.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TagExists(tag.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tag = await _context.Tags.FindAsync(id);
            _context.Tags.Remove(tag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagExists(int id)
        {
            return _context.Tags.Any(e => e.ID == id);
        }
    }
}

BlogMvc/Views/Blog/Create.cshtml
@model BlogMvc.ViewModel.ArticleViewModel 

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArticleDate" class="control-label"></label>
                <input asp-for="ArticleDate" class="form-control" />
                <span asp-validation-for="ArticleDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ArticleTags" class="control-label"></label>
                <input asp-for="ArticleTags" class="form-control" />
                <span asp-validation-for="ArticleTags"class="text-danger"></span> 
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

BlogMvc/Views/Blog/Delete.cshtml
@model BlogMvc.Models.Article

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArticleTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArticleTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArticleDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArticleDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArticleContent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArticleContent)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BlogMvc/Views/Blog/Details.cshtml
@model BlogMvc.Models.Article  

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Article</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArticleTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArticleTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArticleDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArticleDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArticleContent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArticleContent)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ArticleTags)
        </dt>
        <dd class="col-sm-10">
            @foreach (var item in Model.ArticleTags)
            {
               <a href="@Url.Action("Index","Tags", new { @item.TagID } )">@item.Tag.TagName</a>
            }
        </dd>        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BlogMvc/Views/Blog/Edit.cshtml
@model BlogMvc.Models.Article

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="ArticleTitle" class="control-label"></label>
                <input asp-for="ArticleTitle" class="form-control" />
                <span asp-validation-for="ArticleTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArticleDate" class="control-label"></label>
                <input asp-for="ArticleDate" class="form-control" />
                <span asp-validation-for="ArticleDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArticleContent" class="control-label"></label>
                <input asp-for="ArticleContent" class="form-control" />
                <span asp-validation-for="ArticleContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlogMvc/Views/Blog/Index.cshtml
@model IEnumerable<BlogMvc.Models.Article>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ArticleTitle)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.ArticleDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArticleContent)
            </th>
            <th>
                @Html.DisplayNameFor(model =>model.ArticleTags)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ArticleTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArticleDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArticleContent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArticleTags)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>